// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelRouteAPI.Data;

#nullable disable

namespace TravelRouteAPI.Data.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20250314140315_CreateTableTravelRoute")]
    partial class CreateTableTravelRoute
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelRouteAPI.Models.TravelRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TravelRoutes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Destination = "BRC",
                            Origin = "GRU",
                            Price = 10
                        },
                        new
                        {
                            Id = 2,
                            Destination = "SCL",
                            Origin = "BRC",
                            Price = 5
                        },
                        new
                        {
                            Id = 3,
                            Destination = "CDG",
                            Origin = "GRU",
                            Price = 75
                        },
                        new
                        {
                            Id = 4,
                            Destination = "SCL",
                            Origin = "GRU",
                            Price = 20
                        },
                        new
                        {
                            Id = 5,
                            Destination = "ORL",
                            Origin = "GRU",
                            Price = 56
                        },
                        new
                        {
                            Id = 6,
                            Destination = "CDG",
                            Origin = "ORL",
                            Price = 5
                        },
                        new
                        {
                            Id = 7,
                            Destination = "ORL",
                            Origin = "SCL",
                            Price = 20
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
